import { groth16 } from 'snarkjs'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// ── ZK Proof Verification (server-side) ──
//
// Verifies a Groth16 ZK proof generated by the BalanceThresholdSimple circuit.
// The proof demonstrates that the prover holds a balance >= threshold
// without revealing the balance, address, or salt.
//
// The verification key is loaded from the circuits build directory.
// The nullifier is checked for replay protection and persisted to disk.

// Circuit artifacts can be in several locations depending on deployment:
const CIRCUIT_BUILD_DIRS = [
  path.resolve(__dirname, '..', '..', 'circuits', 'build'),
  path.resolve(__dirname, '..', 'circuits', 'build'),
  path.resolve(process.cwd(), 'circuits', 'build')
]

// Nullifier persistence: stored in the data directory alongside hypercore data
const DATA_DIR = process.env.DATA_DIR || './data'
const NULLIFIER_FILE = path.resolve(DATA_DIR, 'zk-nullifiers.json')

function findCircuitDir () {
  for (const dir of CIRCUIT_BUILD_DIRS) {
    if (fs.existsSync(path.join(dir, 'verification_key.json'))) return dir
  }
  return null
}

const VKEY_FILENAME = 'verification_key.json'
const ZKEY_FILENAME = 'circuit_final.zkey'
const WASM_SUBPATH = path.join('main_js', 'main.wasm')

let _vkey = null

function loadVKey () {
  if (_vkey) return _vkey
  const dir = findCircuitDir()
  if (!dir) return null
  try {
    _vkey = JSON.parse(fs.readFileSync(path.join(dir, VKEY_FILENAME), 'utf8'))
    return _vkey
  } catch {
    return null
  }
}

// ── Nullifier persistence ──
// Nullifiers are stored as a JSON set on disk, surviving restarts.
let _nullifiers = null

function loadNullifiers () {
  if (_nullifiers) return _nullifiers
  try {
    const data = fs.readFileSync(NULLIFIER_FILE, 'utf8')
    _nullifiers = new Set(JSON.parse(data))
  } catch {
    _nullifiers = new Set()
  }
  return _nullifiers
}

function saveNullifiers () {
  if (!_nullifiers) return
  try {
    const dir = path.dirname(NULLIFIER_FILE)
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
    // M4 fix: atomic write via temp file + rename
    const tmpFile = NULLIFIER_FILE + '.tmp'
    fs.writeFileSync(tmpFile, JSON.stringify([..._nullifiers]))
    fs.renameSync(tmpFile, NULLIFIER_FILE)
  } catch (err) {
    console.error('[zk] failed to persist nullifiers:', err.message)
  }
}

// H10 fix: Mutex for nullifier check-and-add (concurrency safety)
let _nullifierLock = Promise.resolve()

async function withNullifierLock (fn) {
  const prev = _nullifierLock
  _nullifierLock = (async () => {
    await prev
    return fn()
  })()
  return _nullifierLock
}

// Verify a ZK balance proof
// proof: Groth16 proof object { pi_a, pi_b, pi_c, protocol }
// publicSignals: array [valid, nullifier, threshold, blockNumber, recipientHash]
// expectedThreshold: the minimum balance the server expects (must match circuit public input)
// expectedRecipientHash: the Poseidon hash of the X25519 recipient pubkey
// Returns: { valid, nullifier, blockNumber }
export async function verifyZKBalanceProof (proof, publicSignals, expectedThreshold, expectedRecipientHash) {
  const vkey = loadVKey()
  if (!vkey) {
    return { valid: false, reason: 'ZK verification key not available on this node' }
  }

  // Verify the proof cryptographically
  const isValid = await groth16.verify(vkey, publicSignals, proof)
  if (!isValid) {
    return { valid: false, reason: 'ZK proof verification failed' }
  }

  // Extract public signals: [valid, nullifier, threshold, blockNumber, recipientHash]
  const [validSignal, nullifier, threshold, blockNumber, recipientHash] = publicSignals

  // Check that valid == 1 (balance >= threshold)
  if (validSignal.toString() !== '1') {
    return { valid: false, reason: 'Balance below threshold (valid=0 in proof)' }
  }

  // Check that threshold matches what the server expects
  if (expectedThreshold && BigInt(threshold) < BigInt(expectedThreshold)) {
    return { valid: false, reason: 'Threshold in proof does not meet server requirement' }
  }

  // F2 fix: recipientHash check removed — the circuit doesn't constrain recipientHash
  // in any computation, so checking it provides no cryptographic binding.
  // Replay protection is handled by the nullifier (address + blockNumber).
  // The x25519PubKey binding is enforced by the encrypted key grant itself —
  // only the holder of the X25519 secret key can decrypt the granted keys.

  // H10 fix: Use mutex for concurrency-safe nullifier check-and-add
  const nullifierStr = nullifier.toString()
  const result = await withNullifierLock(() => {
    const nullifiers = loadNullifiers()
    if (nullifiers.has(nullifierStr)) {
      return { valid: false, reason: 'Proof already used (nullifier replay detected)' }
    }
    nullifiers.add(nullifierStr)
    saveNullifiers()
    return null
  })

  if (result) return result

  return {
    valid: true,
    nullifier: nullifierStr,
    blockNumber: blockNumber.toString()
  }
}

// Compute the recipient binding hash from the X25519 public key
// Uses the raw BigInt of the pubkey — simple and deterministic
// The circuit includes this as a public input to bind the proof to a specific recipient
export function computeRecipientHash (x25519PubKeyHex) {
  const bigint = BigInt('0x' + x25519PubKeyHex)
  return bigint.toString()
}

// Check if the circuit artifacts exist on this node
export function hasZKCircuitArtifacts () {
  const dir = findCircuitDir()
  return dir !== null
}

// Get the path to the zkey (for serving to clients who need it)
export function getZKeyPath () {
  const dir = findCircuitDir()
  if (!dir) return null
  const p = path.join(dir, ZKEY_FILENAME)
  return fs.existsSync(p) ? p : null
}

// Get the path to the wasm (for serving to clients who need it)
export function getWasmPath () {
  const dir = findCircuitDir()
  if (!dir) return null
  const p = path.join(dir, WASM_SUBPATH)
  return fs.existsSync(p) ? p : null
}
